spring:
  cloud:
    stream:
      instance-count: 1
      bindings:
        input:
          consumer:
            concurrency: 2
            maxAttempts: 1
          group: geode-sink
          destination: jdbc-event-result
          binder: rabbit
      rabbit:
        bindings:
          input:
            consumer:
              autoBindDlq: true
              republishToDlq: true
              requeueRejected: false
  datasource:
    tomcat:
      max-wait:  300
      min-idle: 10
      max-idle: 100

geode:
  locator: 172.20.7.30
  port: 10334

aggregator:
  groupCount: 2
  batchSize: 1000
  batchTimeout: 1000